## 2 DBs: for influxdb: traffic stats, and for db: traffic operations
apiVersion: v1
kind: Service
metadata:
  name: influxdb 
  namespace: infra
spec:
  selector:
    func: db
    role: stat
  clusterIP: 10.99.0.11
  ports:
    - port: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-stat-db
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: db
      role: stat
  template:
    metadata:
      labels:
        func: db
        role: stat
    spec:
      hostname: influxdb
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 10.99.0.254
      containers:
      - name: stat-db
        image: gabbro:30500/cdn-stat-db
        imagePullPolicy: Never
        env:
        - name: MY_SERVICE_IP
          value: '10.99.0.11'
        ports:
        - containerPort: 8086
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
---
apiVersion: v1
kind: Service
metadata:
  name: db 
  namespace: infra
spec:
  selector:
    func: db
    role: ops
  clusterIP: 10.99.0.10
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-ops-db
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: db
      role: ops
  template:
    metadata:
      labels:
        func: db
        role: ops
    spec:
      hostname: db
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      - name: postgres-data
        emptyDir: {}
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 10.99.0.254
      containers:
      - name: ops-db
        image: gabbro:30500/cdn-ops-db
        imagePullPolicy: Never
        env:
        - name: MY_SERVICE_IP
          value: '10.99.0.10'
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
          - mountPath: /var/lib/postgresql/data
            name: postgres-data
        envFrom:
          - configMapRef:
              name: cdn-config
