## Enroller
apiVersion: v1
kind: Service
metadata:
  name: enroller
  namespace: infra
spec:
  selector:
    func: enroll
  clusterIP: 10.99.0.200
## somehow no port exposing in docker-compose file
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-enroller
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: enroll
  template:
    metadata:
      labels:
        func: enroll
    spec:
      hostname: enroller
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 10.99.0.254
      containers:
      - name: enroller
        image: gabbro:30500/cdn-enroller
        imagePullPolicy: Never
        env:
        - name: MY_SERVICE_IP
          value: '10.99.0.200'
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
---
#vault: create credentials
apiVersion: v1
kind: Service
metadata:
  name: trafficvault
  namespace: infra
spec:
  selector:
    func: secret
  clusterIP: 10.99.0.50
## not sure what these ports for..
  ports:
    - name: port1
      port: 8087
    - name: port2
      port: 8098
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-traffic-vault
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: secret
  template:
    metadata:
      labels:
        func: secret
    spec:
      hostname: trafficvault
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      - name: schema
        persistentVolumeClaim:
          claimName: cdn-schemas
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 10.99.0.254
      containers:
      - name: vault
        image: gabbro:30500/cdn-vault
        imagePullPolicy: Never
        env:
        - name: MY_SERVICE_IP
          value: '10.99.0.50'
        ports:
        - containerPort: 8087
        - containerPort: 8098
        env:
        - name: CLUSTER_NAME
          value: trafficvault
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
          - mountPath: /etc/riak/schemas
            name: schema
        envFrom:
          - configMapRef:
              name: cdn-config
---
#statistic manager: no expose service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-stats
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: stats
  template:
    metadata:
      labels:
        func: stats
    spec:
      hostname: trafficstats
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 10.99.0.254
      containers:
      - name: stats
        image: gabbro:30500/cdn-stats
        imagePullPolicy: Never
        env:
        - name: MY_SERVICE_IP
          #use pod IP instead
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
---
#operation(API) servers: Perl and Go
apiVersion: v1
kind: Service
metadata:
  name: trafficops-perl
  namespace: infra
spec:
  selector:
    func: ops
    lang: perl
  clusterIP: 10.99.0.21
  ports:
    - port: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-ops-perl
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: ops
      lang: perl
  template:
    metadata:
      labels:
        func: ops
        lang: perl
    spec:
      hostname: trafficops-perl
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      - name: ops-ca
        persistentVolumeClaim:
          claimName: cdn-ops-ca
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 10.99.0.254
      containers:
      - name: ops-perl
        image: gabbro:30500/cdn-ops-perl
        imagePullPolicy: Never
        env:
        - name: MY_SERVICE_IP
          value: '10.99.0.21'
        ports:
        - containerPort: 443
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
          - mountPath: /ca
            name: ops-ca
        envFrom:
          - configMapRef:
              name: cdn-config
